# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Health Bars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Health Bars
  pod 'AudioKit',  '4.7.2'

  target 'Health BarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Health BarsUITests' do
    # Pods for testing
  end

end
